import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "@comp/Navbar";
import Sidebar from "@comp/Sidebar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "AR GAMESHOP",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" className={poppins.className}>
      <body>
        <Navbar />
        <Sidebar />

        <main className="ml-64">{children}</main>
      </body>
    </html>
  );
}
